### DISCUSSION TITLE
nginx config when using nginx-proxy + dockergen + acme

### DISCUSSION THREAD

**Discussion by Emporea** [CollaboraOnline/online#4155] [Q&A] [answered]
I am having trouble getting collabora code to work, when using it behind a [nginx proxy managed by docker gen](https://github.com/nginx-proxy/acme-companion/blob/main/docs/Docker-Compose.md).

This is my docker-compose config.
```
version: "3.3"
services:
  collabora:
    image: collabora/code
    cap_add:
      - MKNOD
    environment:
      - username=admin
      - password=password
      - domain=cloud.EXAMPLE.TLD
      - VIRTUAL_HOST=office.EXAMPLE.TLD
      - LETSENCRYPT_HOST=office.EXAMPLE.TLD
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true

networks:
  default:
    external:
      name: nginx-proxy

```
This is working fine so far, I get an
![image](https://user-images.githubusercontent.com/21969523/153316472-4d4e62d0-78c9-418a-b871-e2c8a925ce87.png)
when curling the address.

But I can't get it to work on my nextcloud counterpart. I have read a lot of threads about this topic. I have tried modified my loolwsd file and so much more. Nothing seems to work for me. 

1. https://help.nextcloud.com/t/collabora-configuration-with-docker-compose/3970/7
2. https://github.com/CollaboraOnline/Docker-CODE/issues/49
3. etc.

![image](https://user-images.githubusercontent.com/21969523/153317057-13fe11f2-060e-4ec1-90e9-1bea06f70153.png)

What can I do?

Collabora Container shows no error. Last log is `collabora    | Ready to accept connections on port 9980.`

Edit:

Accessing the collabora via local docker hostname works. But this connection cant be established outside of LAN.
![image](https://user-images.githubusercontent.com/21969523/153318025-af9d107c-e1b8-450e-ae8e-0550c7b1b517.png)
