### DISCUSSION TITLE
HELM Chart - Adding proof key through a secret ?

### DISCUSSION THREAD

**Discussion by vherrlein** [CollaboraOnline/online#7809] [Ideas]
Dear,

Would it be interresting to add a way to setup the Proof Key within the helm chart ?

Currently I'm applying a patch on the helm deployment such as the following:

```yaml
spec:
  template:
    spec:
      volumes:
        - name: proof-key
          secret:
            secretName: collabra-online-proof-key
            items:
              - key: proof_key
                path: proof_key
      containers:
        - name: collabora-online
          volumeMounts:
            - name: proof-key
              mountPath: /etc/coolwsd/proof_key
              subPath: proof_key
              readOnly: true
```

then execute the following to apply it:
`kubectl patch deployment collabora-online -n collabora --patch-file="./deloyment-patch.yaml"`

Regards,
