### ISSUE TITLE
Latest Collabora image wont start

### ISSUE THREAD

**Issue by Tresillo2017** [CollaboraOnline/online#10000]
### Describe the Bug
Collabora on docker won't start

### Steps to Reproduce
1. Create a new compose.yml
2. Start it

### Expected Behavior
To be able to connect and run it

### Actual Behavior
It's just stuck at loading and every time I try to visit the page I get timeout

### Screenshots
```less
collabora  | wsd-00001-00001 2024-09-06 14:45:47.190915 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:46:07.191072 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00027 2024-09-06 14:45:27.191864 +0200 [ prisoner_poll ] TRC  #15: setupPollFds getPollEvents: 0x1| net/Socket.hpp:880
collabora  | wsd-00001-00027 2024-09-06 14:45:27.191870 +0200 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 64000000 size 1| net/Socket.cpp:430
collabora  | wsd-00001-00027 2024-09-06 14:46:31.237286 +0200 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (64000000us)(timedout)| net/Socket.cpp:448
collabora  | wsd-00001-00001 2024-09-06 14:46:27.191227 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:46:47.191403 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:47:07.191794 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:47:27.192309 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00027 2024-09-06 14:46:31.237377 +0200 [ prisoner_poll ] TRC  #15: Handling poll events of prisoner_poll at index 0 (of 1): 0x0| net/Socket.cpp:558
collabora  | wsd-00001-00027 2024-09-06 14:46:31.237407 +0200 [ prisoner_poll ] TRC  #15: setupPollFds getPollEvents: 0x1| net/Socket.hpp:880
collabora  | wsd-00001-00027 2024-09-06 14:46:31.237439 +0200 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 64000000 size 1| net/Socket.cpp:430
collabora  | wsd-00001-00027 2024-09-06 14:47:35.293325 +0200 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (64000000us)(timedout)| net/Socket.cpp:448
collabora  | wsd-00001-00001 2024-09-06 14:47:47.192520 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:48:07.192955 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00027 2024-09-06 14:47:35.293367 +0200 [ prisoner_poll ] TRC  #15: Handling poll events of prisoner_poll at index 0 (of 1): 0x0| net/Socket.cpp:558
collabora  | wsd-00001-00027 2024-09-06 14:47:35.293376 +0200 [ prisoner_poll ] TRC  #15: setupPollFds getPollEvents: 0x1| net/Socket.hpp:880
collabora  | wsd-00001-00027 2024-09-06 14:47:35.293381 +0200 [ prisoner_poll ] TRC  ppoll start, timeoutMicroS: 64000000 size 1| net/Socket.cpp:430
collabora  | wsd-00001-00027 2024-09-06 14:48:39.356860 +0200 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (64000000us)(timedout)| net/Socket.cpp:448
collabora  | wsd-00001-00001 2024-09-06 14:48:27.193395 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
collabora  | wsd-00001-00001 2024-09-06 14:48:47.193535 +0200 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4421
```

### Desktop
(Please complete the following information)
 - **Collabora version:**  1.1.20 
 - **OS and version:** Debian 12 VM
 - **Browser and version:** Zen (Firefox fork) 1.0.0-a.37 (64-bit)

### Additional Context
compose.yml file
```
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - $PWD/config:/config
      - /mnt/ncdata:/data
    ports:
      - 8089:443
      - 8088:80
    restart: unless-stopped
    depends_on:
      - db

  collabora:
    container_name: collabora
    image: collabora/code:latest
    cap_add:
      - MKNOD
    environment:
      - domain=cloud\.tomasps\.com
      - username=redacted
      - password=redacted
    ports:
      - 9980:9980
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --character-set-server=utf8
    volumes:
      - $PWD/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=redacted
      - MYSQL_USER=redacted
      - MYSQL_LOG_ROTATION="max-size=100M max-files=5"
volumes:
  collabora:
     external: true
```
The nextcloud data folder is mounted on a smb share using the following config
`//redacted/nextcloud /mnt/ncdata/ cifs rw,mfsymlinks,seal,credentials=/etc/credentials,uid=1000,gid=1000,file_mode=0770,dir_mode=0770 0 0`

Already tried the previous and it start but I get the following error
```
collabora  \| wsd-00001-00041 2024-09-06 14:35:05.920740 +0200 [ docbroker_001 ] ERR  Failed to add session to [https%3A%2F%2Fcloud.tomasps.com%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1780_ocr26rxhen0c] with URI [https://cloud.tomasps.com/index.php/apps/richdocuments/wopi/files/1780_ocr26rxhen0c?access_token=3nJ41LW5gLA6XEik58bGaUpDH37pu53f&access_token_ttl=0]: WOPI::GetFile [https://cloud.tomasps.com/index.php/apps/richdocuments/wopi/files/1780_ocr26rxhen0c/contents?access_token=&access_token_ttl=0] failed: []\| wsd/DocumentBroker.cpp:3023
--
2 | collabora  \| wsd-00001-00041 2024-09-06 14:35:05.920778 +0200 [ docbroker_001 ] ERR  Storage error while starting session on https%3A%2F%2Fcloud.tomasps.com%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F1780_ocr26rxhen0c for socket #33. Terminating connection. Error: WOPI::GetFile [https://cloud.tomasps.com/index.php/apps/richdocuments/wopi/files/1780_ocr26rxhen0c/contents?access_token=&access_token_ttl=0] failed: []\| wsd/RequestVettingStation.cpp:434
3 | collabora  \| wsd-00001-00041 2024-09-06 14:35:05.921556 +0200 [ docbroker_001 ] ERR  #33: Socket write returned -1 (EPIPE: Broken pipe)\| net/Socket.hpp:1483
4 | collabora  \| wsd-00001-00041 2024-09-06 14:35:05.921650 +0200 [ docbroker_001 ] WRN  ClientSession must be known\| wsd/DocumentBroker.cpp:4058
5 | collabora  \| wsd-00001-00041 2024-09-06 14:35:05.930130 +0200 [ docbroker_001 ] WRN  #28: Unassociated Kit (40) disconnected unexpectedly\| wsd/COOLWSD.cpp:3720
6 | collabora  \| wsd-00001-00041 2024-09-06 14:35:05.930169 +0200 [ docbroker_001 ] WRN  #28: Unknown Kit process closed with pid -1\| wsd/COOLWSD.cpp:3727
7 | collabora  \| sh: 1: /usr/bin/coolmount: Operation not permitted
```
