### ISSUE TITLE
SSLv3 Certificate Unknown

### ISSUE THREAD

**Issue by martadinata666** [CollaboraOnline/online#10911]
### Describe the Bug
Nextcloud instance can't connect to Collabora Online instance

### Steps to Reproduce
1. Deploy docker collabora, compose file
```
services:
  app:
    image: collabora/code:latest
    ports:
      - 9980:9980
    environment:
      - aliasgroup1=https://192.168.0.2:8080
      - aliasgroup2=https://nextcloud.ddyms.my.id
      - extra_params=--o:ssl.ssl_verification=false
    restart: unless-stopped
    networks:
      - collabora
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  collabora:
    name: collabora

```
3. Try connect to collabora instance, check disable certificate verification
4. Error Log
```
app-1  | wsd-00001-00028 2025-01-12 15:49:59.041475 +0000 [ websrv_poll ] ERR  #28: Error while handling poll at 0 in websrv_poll: #28 (handshake): unknown. BIO error: 167773206: error:0A000416:SSL routines::sslv3 alert certificate unknown:
app-1  | C0E67F53F37A0000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1605:SSL alert number 46
app-1  | | net/Socket.cpp:649


```

### Expected Behavior
Should be connect without care of SSL condition

### Actual Behavior
Failed connect due to SSL error certificate unknown

### Screenshots

![2025-01-12-22:48:28-screenshot](https://github.com/user-attachments/assets/ef63430d-a49a-49c3-bd76-0c003a23ed2b)

### Docker deployment
 - **Collabora version:** [24.04.11.2]
 - **Nextcloud version:** [30.0.4]

### Additional Context
Maybe related to #8627
