### ISSUE TITLE
`ssl.enable` is being ignored

### ISSUE THREAD

**Issue by herrlegno** [CollaboraOnline/online#11115]
### Describe the Bug
Applying `ssl.termination` parameter ignores `ssl.enable` parameter

### Steps to Reproduce
1. Run a docker-compose.yml
```yml
services:
  collabora:
    image: collabora/code
    container_name: collabora
    ports:
        - "9980:9980"
    restart: unless-stopped
    environment:
        - extra_params=--o:ssl.enable=false --o:ssl.termination=true
        - domain=192.168.1.30
        - username=whatever
        - password=whatever         
```
3. Navigate to `/hosting/discovery` 
### Expected Behavior
URLs are using `http`

### Actual Behavior
URLs are using `https`

### Screenshots
![Image](https://github.com/user-attachments/assets/1f275b2f-2aa2-402b-9276-d665f42b8531)

### Desktop
(Please complete the following information)
 - **Collabora version**: latest docker version

### Related:
https://github.com/truenas/apps/issues/1578
