### ISSUE TITLE
Issues with HTTP Status Moved (Permanently) HTTP 301  Nextcloud, Collabora & Nginx Reverse Proxies

### ISSUE THREAD

**Issue by ksaadDE** [CollaboraOnline/online#11287]
### Describe the Bug
When having everything properly configured (including nextcloud), the collabora system tries to grab the preset from an url, when opening a document in nextcloud.

If the preset pull response status is 301 (HTTP STATUS 301 / PERMANENTLY MOVED) e.g. due to one or multiple nginx reverse proxies, it will automatically break and report failure.

### Steps to Reproduce
1. Install nextcloud latest & collabora/code latest via docker (configure everything, including the nginx reverse proxies etc)
3. Go in the nextcloud and load a document (.odt)
4. `docker logs collabora` (shows the `Failed to get settings json from [http://http_nextcloud.domain/index.php/apps/richdocuments/wopi/settings?type=systemconfig&access_token=xxxxx&fileId=-1] with status[Moved Permanently]|wsd/DocumentBroker.cpp:1820`)
5. Install older tag e.g. `collabora/code:24.04.10.1.1` (this one shall work)

### Expected Behavior
Installation just loads and allows editing of the documents via nextcloud using collabora/code container behind nginx reverse proxies

### Actual Behavior
The loading of the preset fails, due to Permanently Moved, as only HTTP STATUS OK is being checked for, thus the whole execution is aborted. See suggested patch below.

### Additional Context
please read https://github.com/CollaboraOnline/online/commit/3ed4b490fc84868c6dab7a2aa62eac6b3182286#r153381554

Not sure if this belongs to online but it has the bug in the same code base so

**Comment by ksaadDE** [comment]
@Rash419

**Comment by ksaadDE** [comment]
Short summary of the troublesome line as mentioned in the commit & commentary: https://github.com/CollaboraOnline/online/commit/3ed4b490fc84868c6dab7a2aa62eac6b3182286#r153381554
```cpp
if (presetHttpResponse->statusLine().statusCode() != http::StatusCode::OK) 
{
// ...
}
```

The required patch could be:
```cpp
if (presetHttpResponse->statusLine().statusCode() != http::StatusCode::OK && 
presetHttpResponse->statusLine().statusCode() != http::StatusCode::MovedPermanently) 
{
//...
}
```
Surely, there is a more smart and dynamic alternative (C++ is not my main business) to exclude various HTTP codes that shall not negatively affect the continuation of the processing!

I found the statusCode enum in https://github.com/CollaboraOnline/online/blob/3ed4b490fc84868c6dab7a2aa62eac6b3182286d/net/HttpRequest.hpp

As the containers of two months ago are working fine with fixed version. Just the latest tag breaks.

**Comment by Rash419** [comment]
Thank you for the report. I will check in few hours 🙂

**Comment by Rash419** [comment]
@ksaadDE Hey, can you share your nginx config ?

**Comment by Rash419** [comment]
I tried reproducing the problem with following nginx config and docker compose:


`nginx.conf`

```
worker_processes 1;
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Proxy for Nextcloud
        server_name nextcloud.local;
        location / {
            proxy_pass http://nextcloud:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;

        # Proxy for Collabora Online
        server_name collabora.local;

        # static files
        location ^~ /browser {
          proxy_pass http://collabora:9980;
          proxy_set_header Host $host;
        }


        # WOPI discovery URL
        location ^~ /hosting/discovery {
          proxy_pass http://collabora:9980;
          proxy_set_header Host $host;
        }


        # Capabilities
        location ^~ /hosting/capabilities {
          proxy_pass http://collabora:9980;
          proxy_set_header Host $host;
        }


        # main websocket
        location ~ ^/cool/(.*)/ws$ {
          proxy_pass http://collabora:9980;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_read_timeout 36000s;
        }


        # download, presentation and image upload
        location ~ ^/(c|l)ool {
          proxy_pass http://collabora:9980;
          proxy_set_header Host $host;
        }


        # Admin Console websocket
        location ^~ /cool/adminws {
          proxy_pass http://collabora:9980;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_read_timeout 36000s;
        }

        location / {
            proxy_pass http://collabora:9980;
            proxy_set_header Host $host;
        }
    }
}
```

`docker-compose.yml`:
```
version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
      - collabora

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    volumes:
      - ./nextcloud/data:/var/www/html
    extra_hosts:
      - "collabora.local:192.168.1.12"

  # Collabora Online (CODE)
  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: always
    environment:
      - aliasgroup1=http://nextcloud.local
      - extra_params=--o:ssl.enable=false --o:logging.level=information
      - username=admin
      - password=admin
    extra_hosts:
      - "nextcloud.local:192.168.1.12"

```
