### ISSUE TITLE
Failed to start an async CheckFileInfo request > Invalid URI or access denied to

### ISSUE THREAD

**Issue by tony-engineering** [CollaboraOnline/online#11294]
### Describe the Bug
When I'm trying to open a docx document I get "" message in nextcloud, and this in collabora logs.
```
wsd-00001-00035 2025-03-07 13:04:52.331556 +0000 [ websrv_poll ] ERR  #30: Failed to start an async CheckFileInfo request| wsd/wopi/CheckFileInfo.cpp:159
wsd-00001-00035 2025-03-07 13:04:52.331850 +0000 [ websrv_poll ] ERR  #30: WOPI::CheckFileInfo failed for URI [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=xpHnM7P17P7XYijg9NUOl0kjn0IJAHg4&access_token_ttl=0]: 0 (Unknown) . Headers: 	Body: []| wsd/wopi/CheckFileInfo.cpp:102
wsd-00001-00035 2025-03-07 13:04:52.331869 +0000 [ websrv_poll ] ERR  #30: Invalid URI or access denied to [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=xpHnM7P17P7XYijg9NUOl0kjn0IJAHg4&access_token_ttl=0]| wsd/wopi/CheckFileInfo.cpp:120
wsd-00001-00035 2025-03-07 13:04:52.692811 +0000 [ websrv_poll ] ERR  #28: CheckFileInfo failed for [https%3A%2F%2Fcloud2.rougeot-ant.one%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F106_ocl53d5n2uqw], State::Fail| wsd/RequestVettingStation.cpp:353
```
I tried to tweak aliasgroups but didn't help.

### Steps to Reproduce
Setup nextcloud, ingress-nginx and collabora using helm charts. Here are the values:
collabora:
```
replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
    # block admin urls from outside
    nginx.ingress.kubernetes.io/server-snippet: |
     location /cool/getMetrics { deny all; return 403; }
     location /cool/adminws/ { deny all; return 403; }
     location /browser/dist/admin/admin.html { deny all; return 403; }

    kubernetes.digitalocean.com/certificate-id: "d4549a8d-7160-45a5-b6f3-449c74455cba"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: collabora.cloud2.rougeot-ant.one
      paths:
      - path: /
        pathType: ImplementationSpecific

autoscaling:
  enabled: false

collabora:
  aliasgroups:
    - host: "collabora.cloud2.rougeot-ant.one,cloud2.rougeot-ant.one,https://cloud2.rougeot-ant.one"
  extra_params: --o:ssl.enable=false --o:ssl.termination=true
  # for production enviroment we recommend appending `extra_params` with `--o:num_prespawn_children=4`. It defines number of child processes to keep started in advance and waiting for new clients

resources:
  limits:
    cpu: "1000m"
    memory: "1000Mi"
  requests:
    cpu: "1000m"
    memory: "1000Mi"
```

### Expected Behavior
I can open documents

### Actual Behavior
I can't open document

### Screenshots

![Image](https://github.com/user-attachments/assets/57e99a0d-56f4-43e0-b2a7-926c7817729e)

### Desktop

 - **Collabora version:** Collabora Online Development Edition 24.04.12.2
 - **OS and version:** Running in Digital Ocean Kubernetes Cluster
 - **Browser and version:** Firefox

### Smartphone
(Please complete the following information)
 - **Device:** [e.g. iPhone 14]
 - **OS:** [e.g. iOS 16.5]
 - **Browser and version:** [e.g. Safari 16.4]

### Additional Context
-

**Comment by Darshan-upadhyay1110** [comment]
Hello @tony-engineering i see `http` in alias group. the `aliasgroups` should not include the protocol (https://)

Then try to Manually test WOPI using curl from within the Collabora pod:

```
curl -k -I "https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=xpHnM7P17P7XYijg9NUOl0kjn0IJAHg4"
```

**Comment by tony-engineering** [comment]
Hello Drashan, thanks for assisting me with this issue !

I made the change you suggested:
```
collabora:
  aliasgroups:
    - host: "collabora.cloud2.rougeot-ant.one,cloud2.rougeot-ant.one"
  extra_params: --o:ssl.enable=false --o:ssl.termination=true
  # for production enviroment we recommend appending `extra_params` with `--o:num_prespawn_children=4`. It defines number of child processes to keep started in advance and waiting for new clients
```
I got same error message in logs
```
wsd-00001-00035 2025-03-12 18:22:26.864549 +0000 [ websrv_poll ] ERR  #29: Failed to start an async CheckFileInfo request| wsd/wopi/CheckFileInfo.cpp:159
wsd-00001-00035 2025-03-12 18:22:26.864668 +0000 [ websrv_poll ] ERR  #29: WOPI::CheckFileInfo failed for URI [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv&access_token_ttl=0]: 0 (Unknown) . Headers: 	Body: []| wsd/wopi/CheckFileInfo.cpp:102
wsd-00001-00035 2025-03-12 18:22:26.864680 +0000 [ websrv_poll ] ERR  #29: Invalid URI or access denied to [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv&access_token_ttl=0]| wsd/wopi/CheckFileInfo.cpp:120
wsd-00001-00035 2025-03-12 18:22:27.307332 +0000 [ websrv_poll ] ERR  #30: CheckFileInfo failed for [https%3A%2F%2Fcloud2.rougeot-ant.one%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F106_ocl53d5n2uqw], State::Fail| wsd/RequestVettingStation.cpp:353
wsd-00001-00035 2025-03-12 18:22:28.173083 +0000 [ websrv_poll ] ERR  #32: Failed to start an async CheckFileInfo request| wsd/wopi/CheckFileInfo.cpp:159
wsd-00001-00035 2025-03-12 18:22:28.173353 +0000 [ websrv_poll ] ERR  #32: WOPI::CheckFileInfo failed for URI [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv&access_token_ttl=0&permission=edit]: 0 (Unknown) . Headers: 	Body: []| wsd/wopi/CheckFileInfo.cpp:102
wsd-00001-00035 2025-03-12 18:22:28.173479 +0000 [ websrv_poll ] ERR  #32: Invalid URI or access denied to [https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv&access_token_ttl=0&permission=edit]| wsd/wopi/CheckFileInfo.cpp:12
```
I tried to curl the url given in logs from my machine and it worked
```
curl -vL https://cloud2.rougeot-ant.one/index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw\?access_token\=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv\&access_token_ttl\=0
*   Trying 146.190.207.91:443...
* Connected to cloud2.rougeot-ant.one (146.190.207.91) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.cloud2.rougeot-ant.one
*  start date: Feb 28 11:09:03 2025 GMT
*  expire date: May 29 11:09:02 2025 GMT
*  subjectAltName: host "cloud2.rougeot-ant.one" matched cert's "cloud2.rougeot-ant.one"
*  issuer: C=US; O=Let's Encrypt; CN=E6
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /index.php/apps/richdocuments/wopi/files/106_ocl53d5n2uqw?access_token=Qd3mUAHOA8fh1tGxqwgJyerCA85wUucv&access_token_ttl=0 HTTP/1.1
> Host: cloud2.rougeot-ant.one
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Wed, 12 Mar 2025 18:23:12 GMT
< content-type: application/json; charset=utf-8
< content-length: 946
< referrer-policy: no-referrer
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-robots-tag: noindex, nofollow
< x-xss-protection: 1; mode=block
< x-powered-by: PHP/8.2.27
< set-cookie: ocl53d5n2uqw=53f52aeb97c9740759906d1aa73ecb33; path=/; HttpOnly; SameSite=Lax
< set-cookie: oc_sessionPassphrase=I6TvDXXUQC2sbuKG5Hoe0CruoPjT1HEAsj6LuqqVxYIT%2B1Q3nuWLSav6TsqxJWkCfyB7yD5f5LD80pqQ%2BQxHK62TzslhK%2F%2BOwQNCoqcYnLoTIxPy%2Ba0R45Gky8bS8TYf; path=/; HttpOnly; SameSite=Lax
< set-cookie: ocl53d5n2uqw=53f52aeb97c9740759906d1aa73ecb33; path=/; HttpOnly; SameSite=Lax
< content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
< set-cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< set-cookie: ocl53d5n2uqw=53f52aeb97c9740759906d1aa73ecb33; path=/; HttpOnly; SameSite=Lax
< x-request-id: rltzpKExxDgNPjjWbjOZ
< cache-control: no-cache, no-store, must-revalidate
< feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
< 
* Connection #0 to host cloud2.rougeot-ant.one left intact
{"BaseFileName":"Welcome to Nextcloud Hub.docx","Size":24295,"Version":"0","UserId":"joJoC7DH","OwnerId":"joJoC7DH","UserFriendlyName":"joJoC7DH","UserExtraInfo":{"avatar":"http:\/\/cloud2.rougeot-ant.one\/avatar\/joJoC7DH\/64","is_admin":true},"UserPrivateInfo":{"ZoteroAPIKey":"","SignatureCert":"","SignatureKey":"","SignatureCa":""},"UserCanWrite":true,"UserCanNotWriteRelative":false,"PostMessageOrigin":"http:\/\/cloud2.rougeot-ant.one\/","LastModifiedTime":"2025-02-28T16:04:23.000000Z","SupportsRename":true,"UserCanRename":true,"EnableInsertRemoteImage":true,"EnableInsertRemoteFile":true,"EnableShare":true,"HideUserList":"","EnableOwnerTermination":true,"DisablePrint":false,"DisableExport":false,"DisableCopy":false,"HideExportOption":false,"HidePrintOption":false,"DownloadAsPostMessage":false,"SupportsLocks":false,"IsUserLocked":false,"EnableRemoteLinkPicker":true,"HasContentRange":true,"IsAdminUser":true,"IsAnonymousUser":false}%       
```

Do you have another idea what I can try ?
