### ISSUE TITLE
collabora/code now working on Nextcloud Office

### ISSUE THREAD

**Issue by farukerdem34** [CollaboraOnline/online#11521]
I’ve been researching this error for a few days but I haven’t found any solution. I can’t work with `collabora/code` Nextcloud Office. Both `collabora/code` and Nextcloud work with Docker.

Both `collabora/code` and nextcloud work on my Raspberry Pi 5.

Nextcloud compose file:

```yaml
volumes:                                                                                                                                                                                                     
  nextcloud:
  db:

services:
  nextcloud-db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - /mnt/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - shared
      - nextcloud
networks:
  shared:
    external: true
  nextcloud:
```

`collabora/code` compose file:

```yaml
services:
  collabora:
    image: collabora/code:latest
    privileged: true
    container_name: 'collabora'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/colla/images:/usr/share/coolwsd/browser/dist/images
    ports:
      - 9980:9980/tcp
    restart: always
    environment:
      - server_name=code\.domain\.com
      - extra_params=--o=ssl.enable=false --o:ssl.termination=false --o:admin_console.username=admin --o:admin_console.password=pass
    cap_add:
      - MKNOD

```
Nginx config for `collabora/code`

```
server {

	listen 443 ssl;

	server_name code.domain.com;


	ssl_certificate /etc/ssl/code.domain.com/certificate.crt;

	ssl_certificate_key /etc/ssl/code.domain.com/private.key;


	# static files
	location ^~ /browser {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# WOPI discovery URL
	location ^~ /hosting/discovery {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# Capabilities
	location ^~ /hosting/capabilities {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# main websocket
	location ~ ^/cool/(.*)/ws$ {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Upgrade $http_upgrade;

		proxy_set_header Connection "Upgrade";

		proxy_set_header Host $host;

		proxy_read_timeout 36000s;

	}


	# download, presentation and image upload
	location ~ ^/(c|l)ool {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# Admin Console websocket
	location ^~ /cool/adminws {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Upgrade $http_upgrade;

		proxy_set_header Connection "Upgrade";

		proxy_set_header Host $host;

		proxy_read_timeout 36000s;

	}

}
```

```bash
❯ curl localhost:9980
OK
```

```bash
❯ curl 10.0.0.1:9980
OK
```

The error got from Nextcloud Web UI:

![Image](https://github.com/user-attachments/assets/8d25f445-790b-469c-b749-704919c1dd66)

The error from `collabora/code`:

```
collabora  | wsd-00001-00028 2025-04-03 12:30:50.121787 +0100 [ websrv_poll ] ERR  Failed to get settings json from [http://skycloud.domain.com/index.php/apps/richdocuments/wopi/settings?type=systemconfig&access_token=oJaOQH5sIvsjcB5sN0RFBgSgtrd1nJJq&fileId=-1] with status[Moved Temporarily]| wsd/DocumentBroker.cpp:1805
collabora  | wsd-00001-00028 2025-04-03 12:30:50.122090 +0100 [ websrv_poll ] ERR  Failed to install config [shared-http_skycloud.domain.com/index.php/apps/richdocuments/wopi/settings-67edec761823367ed2974aad0d]| wsd/RequestVettingStation.cpp:202
```

```bash
❯ curl 'https://skycloud.domain.com/apps/richdocuments/wopi/settings?type=systemconfig&access_token=oJaOQH5sIvsjcB5sN0RFBgSgtrd1nJJq&fileId=-1'
```
Output
```json
{"kind":"shared","autotext":[],"template":[]}                                                                                                                                                            ```
```
