### ISSUE TITLE
sh: 1: /usr/bin/coolmount: Operation not permitted

### ISSUE THREAD

**Issue by farukerdem34** [CollaboraOnline/online#11525]
I’ve been researching this error for a few days but I haven’t found any solution. I can’t work with collabora/code Nextcloud Office. Both collabora/code and Nextcloud work with Docker.

Both collabora/code and nextcloud work on my Raspberry Pi 5.

Nextcloud compose file:

```yaml
volumes:                                                                                                                                                                                                     
  nextcloud:
  db:

services:
  nextcloud-db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-db
    volumes:
      - /mnt/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    networks:
      - shared
      - nextcloud
networks:
  shared:
    external: true
  nextcloud:
```

collabora/code compose file:


```yaml
services:
  collabora:
    image: collabora/code:24.04.13.1.1
    container_name: 'collabora'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - images:/usr/share/coolwsd/browser/dist/images
      - collabora:/opt
    ports:
      - 9980:9980/tcp
    restart: always
    environment:
      - aliasgroup1=https://skycloud.domain.com:443,https://skycloud\\.domain\\.com:443
      - extra_params=--o=ssl.enable=false --o:ssl.termination=true --o:admin_console.username=admin --o:admin_console.password=admin --o:user_interface.mode=compact --o:logging.level=warning
    cap_add:
      - MKNOD
volumes:
  collabora:
  images:
```

Nginx config for collabora/code

```
server {

	listen 443 ssl;

	server_name code.domain.com;


	ssl_certificate /etc/ssl/code.domain.com/certificate.crt;

	ssl_certificate_key /etc/ssl/code.domain.com/private.key;


	# static files
	location ^~ /browser {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# WOPI discovery URL
	location ^~ /hosting/discovery {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# Capabilities
	location ^~ /hosting/capabilities {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# main websocket
	location ~ ^/cool/(.*)/ws$ {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Upgrade $http_upgrade;

		proxy_set_header Connection "Upgrade";

		proxy_set_header Host $host;

		proxy_read_timeout 36000s;

	}


	# download, presentation and image upload
	location ~ ^/(c|l)ool {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Host $host;

	}


	# Admin Console websocket
	location ^~ /cool/adminws {

		proxy_pass http://10.0.0.1:9980;

		proxy_set_header Upgrade $http_upgrade;

		proxy_set_header Connection "Upgrade";

		proxy_set_header Host $host;

		proxy_read_timeout 36000s;

	}

}
```

```
❯ curl localhost:9980
OK
```

```
❯ curl 10.0.0.1:9980
OK
```

The error log from collabora/code container:

```
collabora  | kit-00036-00036 2025-04-03 14:00:06.024179 +0100 [ kit_spare_002 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00036-00036 2025-04-03 14:00:06.024357 +0100 [ kit_spare_002 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template'| kit/Kit.cpp:595
collabora  | kit-00037-00037 2025-04-03 14:00:06.026411 +0100 [ kit_spare_003 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00037-00037 2025-04-03 14:00:06.026465 +0100 [ kit_spare_003 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template'| kit/Kit.cpp:595
collabora  | kit-00038-00038 2025-04-03 14:00:06.030957 +0100 [ kit_spare_004 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00038-00038 2025-04-03 14:00:06.031013 +0100 [ kit_spare_004 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-c15a7b88/tmp/sharedpresets/template'| kit/Kit.cpp:595
```

```
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | frk-00026-00026 2025-04-03 14:10:42.728854 +0100 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
collabora  | kit-00614-00614 2025-04-03 14:10:42.869987 +0100 [ kit_spare_018 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00614-00614 2025-04-03 14:10:42.870048 +0100 [ kit_spare_018 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template'| kit/Kit.cpp:595
collabora  | wsd-00001-00613 2025-04-03 14:10:43.355399 +0100 [ docbroker_016 ] ERR  #18: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1627
collabora  | wsd-00001-00613 2025-04-03 14:10:43.355464 +0100 [ docbroker_016 ] ERR  #18: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1627
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | frk-00026-00026 2025-04-03 14:10:43.449652 +0100 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
collabora  | kit-00640-00640 2025-04-03 14:10:43.599367 +0100 [ kit_spare_019 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00640-00640 2025-04-03 14:10:43.599430 +0100 [ kit_spare_019 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template'| kit/Kit.cpp:595
collabora  | wsd-00001-00639 2025-04-03 14:10:44.059631 +0100 [ docbroker_017 ] ERR  #18: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1627
collabora  | wsd-00001-00639 2025-04-03 14:10:44.059713 +0100 [ docbroker_017 ] ERR  #18: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1627
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | frk-00026-00026 2025-04-03 14:10:48.653966 +0100 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
collabora  | kit-00666-00666 2025-04-03 14:10:48.759428 +0100 [ kit_spare_01a ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00666-00666 2025-04-03 14:10:48.759502 +0100 [ kit_spare_01a ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/template'| kit/Kit.cpp:595
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | frk-00026-00040 2025-04-03 14:10:49.736277 +0100 [ subforkit_001 ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
collabora  | kit-00678-00678 2025-04-03 14:10:49.825446 +0100 [ kit_spare_00b ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/shared-http_skycloud.yildizskylab.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Fsettings-67edec761823367ed2974aad0d/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00678-00678 2025-04-03 14:10:49.825518 +0100 [ kit_spare_00b ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/shared-http_skycloud.yildizskylab.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Fsettings-67edec761823367ed2974aad0d/template'| kit/Kit.cpp:595
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | sh: 1: /usr/bin/coolmount: Operation not permitted
collabora  | frk-00026-00040 2025-04-03 14:11:18.962082 +0100 [ subforkit_001 ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
collabora  | kit-00694-00694 2025-04-03 14:11:19.049550 +0100 [ kit_spare_00c ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/shared-http_skycloud.yildizskylab.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Fsettings-67edec761823367ed2974aad0d/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
collabora  | kit-00694-00694 2025-04-03 14:11:19.049690 +0100 [ kit_spare_00c ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-d15c0017/tmp/sharedpresets/shared-http_skycloud.yildizskylab.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Fsettings-67edec761823367ed2974aad0d/template'| kit/Kit.cpp:595
```
