### ISSUE TITLE
No way to do healthchecks in newer Docker image 25.04 due to curl being removed

### ISSUE THREAD

**Issue by savely-krasovsky** [CollaboraOnline/online#11856]
### Is your feature request related to a problem?

After CODE 25.04 release docker image hasn't `curl` inside image. After that change there is no way to check CODE status and write healthcheck.

### Describe the solution you'd like

Bring `curl` inside image back.

### Describe alternatives you've considered

Create custom command to check that CODE is ready to serve requests

**Comment by jazevedo-coll** [comment]
I can confirm this issue with: collabora/code:25.04.1.1.1

**Comment by savely-krasovsky** [comment]
Temporary patch for `podman` healthcheck:
```
["/bin/bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\\r\\nHost: localhost:9980\\r\\n\\r\\n' >&3 && head -n 1 <&3 | grep '200 OK'"]
```
I wouldn't call it a solution since it's too obscure.

**Comment by timar** [comment]
@savely-krasovsky can please elaborate a bit this use case. How do you use curl inside the docker container for health checks? We do not want to break useful features, on the other hand there is a demand to keep the image minimal (not the size, rather the complexity).

**Comment by mritzmann** [comment]
> can please elaborate a bit this use case.

My use case: Since the image has no health check, I created one.

<details>

<summary>my composer.yml with a healthcheck</summary>

```yml
services:
  collabora:
    image: collabora/code:25.04.2.1.1
    restart: always
    ports:
      - "127.0.0.1:9980:9980"
    healthcheck:
      test: "curl --max-time 10 --insecure https://127.0.0.1:9980 | grep OK"
```

</details>

However, this is no longer possible for v25:

* There is no `curl` or `wget`, or something else that can do https
* It is not possible to install curl manually, because of [#12021](https://github.com/CollaboraOnline/online/issues/12021)
