### ISSUE TITLE
Disk space usage by /opt/cool/child-roots/  is bloating

### ISSUE THREAD

**Issue by AleftinaT** [CollaboraOnline/online#12120]
### Describe the Bug
Disk space usage by /opt/cool/child-roots/ in /var/lib/docker/overlay2 is bloating, re-use is not working. There are  duplicates of files 
```
5.3M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/tmp
0	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/linkable
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/rfEz0hzKJtqHJWed
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/EGcAU5ftz6pJAZBo
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/RZhkXQUzoWYg3lq0
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/HU98mbaEKALvjTPe
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/RzbNMDZBQ61Pxt3X
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/fhX69IZINf0DsyJk
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/cFKC9QKVhwFSru7E
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/cMh8neKCKoGiIQWy
414M	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800/k8V4Nsy5pyOlq0KD
3.7G	/var/lib/docker/overlay2/41711bc1c3df98781f6bc7e481475eef639563a01a4d83f25f3540033ed2955a/diff/opt/cool/child-roots/7-cc2a7800
```
### Steps to Reproduce
Start nextcloud AIO on alma linux 9

### Expected Behavior
Re-using of linkable files

### Actual Behavior
Storage usage grows 

### Server
 - **Collabora version:** 25.04.2.1
 - **OS and version:** AlmaLinux 9.5 
 - **Docker version:** 28.2.2
 - **Nextcloud version:** 31.0.5

### Additional Context
Errors in log:
```
kit-00175-00175 2025-06-11 08:49:26.602949 +0300 [ kit_spare_005 ] ERR  Failed to stat or chown 65534:65534 /opt/cool/child-roots/7-cc2a7800//linkable/opt/cool/systemplate/etc/copied: Invalid argument missing cap_chown?, disabling linkable| kit/Kit.cpp:459
kit-00175-00175 2025-06-11 08:49:26.603475 +0300 [ kit_spare_005 ] ERR  link("/opt/cool/systemplate/etc/copied", "/opt/cool/child-roots/7-cc2a7800/97P5QjuB2YHkCKGT/etc/copied") failed: Invalid argument. Very slow copying path triggered.| kit/Kit.cpp:475
kit-00175-00175 2025-06-11 08:49:33.020373 +0300 [ kit_spare_005 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/7-cc2a7800/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil-unix.cpp:63
kit-00175-00175 2025-06-11 08:49:33.020573 +0300 [ kit_spare_005 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/7-cc2a7800/tmp/sharedpresets/template'| kit/Kit.cpp:612
```

**Comment by jazevedo-coll** [comment]
@AleftinaT hello, can you tell us what docker variables you use. Or share if possible your docker/podman-compose file after sensitive information is removed?

**Comment by AleftinaT** [comment]
@jazevedo-coll thank you for answering soon) 
collabora is started by nextcloud-aio-mastercontainer 
docker inspect shows envs:
```
"aliasgroup1=https://[my_domain_name]:443",
"extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:mount_jail_tree=false --o:logging.level=warning --o:home_mode.enable=true --o:security.seccomp=true --o:remote_font_config.url=https://[my_domain_name]/apps/richdocuments/settings/fonts.json --o:net.post_allow.host[0]=.+",
"dictionaries=de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru",
"server_name=[my_domain_name]",
"DONT_GEN_SSL_CERT=1",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"LC_CTYPE=C.UTF-8"
```

**Comment by jazevedo-coll** [comment]
@AleftinaT if you restart the container with the flag `--privileged` included does this still occur?

**Comment by AleftinaT** [comment]
> [@AleftinaT](https://github.com/AleftinaT) if you restart the container with the flag `--privileged` included does this still occur?

yes, the same behavior
I also checked capabilities list. here it is:
```
            "CapAdd": [
                "MKNOD",
                "SYS_ADMIN",
                "CHOWN"
            ],
            "CapDrop": [
                "NET_RAW"
            ],
```

**Comment by jazevedo-coll** [comment]
@AleftinaT sorry, I did not noticed that you mentioned AIO, that has a different setup for CODE than a regular CODE docker container. I need to investigate this.

**Comment by haijerc** [comment]
Any news on this?

**Comment by checkmeck** [comment]
I can confirm this issue. I deployed collabora container standalone:

```yaml
services:
  collabora:
    image: collabora/code:latest
    container_name: collabora_app
    cap_add:
      - SYS_ADMIN
      - MKNOD
    ports:
      - 9980:9980
    mem_limit: 28g
    mem_reservation: 12g
    environment:
      - aliasgroup1=https://xxx
      - aliasgroup2=https://xx2
      - 'extra_params= --o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=.+ --o:storage.wopi.host[0]=.+ --o:security.enable_macros_execution=true'
      - dictionaries=de_DE en_US
      - username=admin
      - password=password
    restart: unless-stopped
```
