### ISSUE TITLE
Impossible to add a new word to dictionary

### ISSUE THREAD

**Issue by sy6sy2** [CollaboraOnline/online#12188]
### Describe the Bug

It's impossible to add any word in the spell check dictionary because I get this error:

```
kit-00072-00072 2025-06-20 13:32:26.355519 +0200 [ kitbroker_004 ] ERR  ToMaster-00e: Exception while handling [uno .uno:AddToWordbook?Wordbook:string=List of Ignored Words]: <unspecified file>(1): expected value| common/Session.cpp:331
```

### Steps to Reproduce
1. Create a new doc file
2. Write any misspelled word
3. Click on "Add to dictionary"
4. It does not work, the word is still red underlined

### Expected Behavior
The word should be added to the dictionary.

### Actual Behavior
A clear and concise description of what actually happens.
The word is not added to the dictionary.

### Desktop
(Please complete the following information)
 - **Collabora version:** collabora/code:25.04.3.1.1
 - **OS and version:** Linux Debian 11 (Docker compose stack)
 - **Browser and version:** Safari macOS

### Additional Context

When I open a document on Nextcloud I also have these errors:

```
collabora-1  | wsd-00001-00088 2025-06-20 13:38:06.663471 +0200 [ docbroker_005 ] ERR  Failed to parse viewsetting json with error[JSON Exception], for session[012]| wsd/DocumentBroker.cpp:1667
collabora-1  | wsd-00001-00088 2025-06-20 13:38:10.504946 +0200 [ docbroker_005 ] ERR  Incorrect JSON property [SpellOnline]. Did you mean [spellOnline] ? (Levenshtein distance: 0)| common/JsonUtil.hpp:145
```

This is my current docker compose service of collabora:

```
  collabora:
    image: collabora/code:25.04.3.1.1
    restart: unless-stopped
    logging: *default-logging
    privileged: true
    cap_add:
      - MKNOD
    networks:
      - public
    environment:
      TZ: Europe/Paris
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      server_name: collabora.XXXXXXXXX.org
      aliasgroup1: https://nextcloud.XXXXXXXXX.org
      dictionaries: en_GB en_US fr_FR
```

**Comment by timur-g** [comment]
Please clarify the report. In new Online versions it should be possible to add to dictionary, if you use one.
Do you have Nextcloud 31, did you set wordbook dictionary in Options-Office? Which one, global or personal one?
With all that, seems there is the issue with personal dictionary.

**Comment by sy6sy2** [comment]
I did not add anything, I am using the bare setup of collabora in my nextcloud docker compose stack:

```
  nextcloud:
    image: nextcloud:31.0.6
    restart: unless-stopped
    logging: *default-logging
    networks:
      - public
      - internal
    volumes:
      - ./nextcloud_data:/var/www/html
    environment:
      TZ: Europe/Paris
      NEXTCLOUD_ADMIN_USER: XXXXXX
      NEXTCLOUD_ADMIN_PASSWORD: XXXXXX
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.XXXXXX.org
      MYSQL_DATABASE: XXXXXX
      MYSQL_USER: XXXXXX
      MYSQL_PASSWORD: XXXXXX
      MYSQL_HOST: mariadb
      REDIS_HOST: redis

  collabora:
    image: collabora/code:25.04.3.2.1
    restart: unless-stopped
    logging: *default-logging
    privileged: true
    cap_add:
      - MKNOD
    networks:
      - public
    environment:
      TZ: Europe/Paris
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      server_name: collabora.XXXXXXXXX.org
      aliasgroup1: https://nextcloud.XXXXXXXXX.org
      dictionaries: en_GB en_US fr_FR
```

I did not set anything in Options-Office, should I?
