### ISSUE TITLE
latest docker image doesn't work with nextcloud (X-Frame Error)

### ISSUE THREAD

**Issue by quizilkend** [CollaboraOnline/online#3729]
Hi,
I just updated the CODE docker image to the latest (from 2021-11-25). Afterwards CODE was not reachable from within nextcloud anymore.
Firefox was complaining about xframe-neterror (https://support.mozilla.org/1/firefox/94.0.1/Linux/de/xframe-neterror-page), Chromium didn't want to show anything.

I downgraded to 6.4.14.3 and everything works as expected.

CODE is setup with nextcloud according to those instructions:
https://nextcloud.com/de/collaboraonline/

Best regards.

**Comment by HPPinata** [comment]
Having the same issue on an aarch64 host system, works with :6.4.14.3 but not with :latest so not just a single case.

**Comment by joergmschulz** [comment]
see https://forum.collaboraonline.com/t/cant-open-files-the-server-has-disconnected-admin-page-server-has-been-shut-down-logs-client-server-version-mismatch/707/3

**Comment by Sim0nW0lf** [comment]
I am having similar issues.
Collabora isn't working anymore even tho connection is green. This is the same for my arm64 and amd64 systems.

My system is running Docker version 20.10.10, nextcloud:apache (currently v,22.2.0) with redis and Traefik in [my docker-compose.yml](https://github.com/Sim0nW0lf/Docker-Atelier/blob/master/Nextcloud/docker-compose.yml) on arm64 and also amd64

**Comment by isdnfan** [comment]
just tested upgrade from collabora/code:6.4.10.10 over collabora/code:6.4.13 to collabora/code:21.11.0.3.1 with NC 22.2.3 running in Docker behind traefik reverse proxy - everything works (had to *redetect* Collabora in NC settings after 2nd step - maybe just timing issue)!

![image](https://user-images.githubusercontent.com/18125597/144504148-fe5da2b4-369f-4515-b418-6f6877db7888.png)

```
 collabora:
    image: collabora/code:21.11.0.3.1
    container_name: collabora
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 9980:9980
    expose:
      - "9980"
    environment:
      #should work as "domain=cloud1\.nextcloud\.com|cloud2\.nextcloud\.com"
      - domain=${COLLABORA_DOMAINS}
      - dictionaries=de_DE en_US
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=${COLLABORA_FQDN}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:user_interface.mode=classic --o:logging.level=warning --o:net.proto=IPv4
      - username=${redisuser}
      - password=${redispwd}
    cap_add:
      - MKNOD
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_FQDN}`)"
      # unused because of https redirect on traefik web endpoint
      #- "traefik.http.routers.collabora.entrypoints=web"
      #- "traefik.http.middlewares.collabora-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.collabora.middlewares=https-redirect@file"
      - "traefik.http.routers.collabora-secure.entrypoints=web-secure"
      - "traefik.http.routers.collabora-secure.rule=Host(`${COLLABORA_FQDN}`)"
      - "traefik.http.routers.collabora-secure.tls=true"
      - "traefik.http.routers.collabora-secure.tls.certresolver=letsencryptresolver"
      - "traefik.passHostHeader=true"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
