### ISSUE TITLE
Failure to load Collabora in Nextcloud

### ISSUE THREAD

**Issue by mike-lloyd03** [CollaboraOnline/online#4090]
**Describe the bug**
When running Nextcloud and Collabora in Docker containers, Nextcloud reports the following error when trying to open a document:

```
Failed to load Collabora Online Development Edition - please try again later
```

Going to the admin web interface gives this error:

```
Server has been shut down; please reload the page.
```

Reloading the pages gives the same error.

This is occurring even though the CODE page in Nextcloud settings says it can reach the Collabora server. I can also curl the Collabora server from the Nextcloud container and get a 200 response.

**To Reproduce**
SSL is disabled and SSL Termination is enabled in Collabora via docker environment variables. Both are in the same docker compose file and this all sits behind an nginx reverse proxy which provides SSL encryption.

Docker Compose file:
```
version: '3'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - /mnt/data/nextcloud/db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: unless-stopped

  app:
    image: nextcloud:22-apache
    hostname: nc.presidio.blue
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/nextcloud/data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
      - code


  cron:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - /mnt/data/nextcloud/data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
        
  code:
    image: collabora/code:21.11.1.4.1
    restart: unless-stopped
    networks:
      - default
      - code
    env_file:
      - .env
    ports:
      - 9980:9980
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
    cap_add:
      - MKNOD
    environment:
      - "extra_params=--o:ssl.termination=true --o:ssl.enable=false" 

networks:
  proxy-tier:
  code:
    driver: bridge
```

**Expected behavior**
Open Document Format files should open in the Collabora online editor

**Actual behavior**
Document fails to load with an error.

Server:
- OS: Arch Linux 5.16.14
- Nextcloud Version: 22.2.3
- Collabora Version: 21.11.1.4.1
- Docker Version: 20.10.12
