### ISSUE TITLE
DNS resolve error since last update

### ISSUE THREAD

**Issue by NaggingDaivy** [CollaboraOnline/online#4480]
**Describe the bug**
Since last update, Collabora has a "DNS resolve" errror.
**To Reproduce**

1. Create docker instance via docker-compose:

```
version: '3'

services:
  collabora-code:
    image: collabora/code
    container_name: collabora-code
    cap_add:
      - MKNOD
    environment:
      - username=USERNAME
      - password=PASSWORD
      - dictionaries=fr_FR en_US
      - domain=nextcloud\\.domain\\.com

    ports:
      - 9980:9980
    restart: always
```
 

2. Connect both Nextcloud to Collabora

**Expected behavior**
Both should work

**Actual behavior**
Collabora is only looking at the IP and not the nextcloud hostname since last update, so both can't connect. Instead of looking for "nextcloud.domain.com", it looks at the IP behind it, which is proxied within Cloudflare. When I disable the Cloudflare proxy and using my real IP, the same issue occurs, so it is not a Cloudflare issue. Here is a error log :

```
wsd-00001-00041 2022-03-25 15:30:17.066960 +0000 [ websrv_poll ] ERR  Poco::Net::DNS::resolve("162.158.233.69") failed: Host not found: 162.158.233.69| wsd/COOLWSD.cpp:3015
wsd-00001-00041 2022-03-25 15:30:17.067047 +0000 [ websrv_poll ] WRN  convert-to: Requesting address is denied: 162.158.233.69| wsd/COOLWSD.cpp:3021
```
