### ISSUE TITLE
Use of domain variable is not supported

### ISSUE THREAD

**Issue by tuxfy** [CollaboraOnline/online#4594]
**Describe the bug**
The env variable domain is not working anymore.

**To Reproduce**
```
services:
  collabora:
    image: collabora/code:21.11.3.6.1
    restart: always
    container_name: collabora
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    environment:
      - domain=nc-domain\\.name\\.com
      - username=
      - password=
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
```

**Expected behavior**
Works as before in combination with **one** Nextcloud instance. I'm not using multiple domains or aliases.
Without manual changes on /etc/coolwsd/coolwsd.xml

**Actual behavior**
`docker logs `

```
-e ERR: Use of domain variable is not supported. First host/domain who tries to connect to COOL is always allowed.
To allow multiple host and its aliases use something like this and pass it as env variable:
aliasgroup1=https://domain1:443,https://its-alias|its-second-alias:443 
aliasgroup2=https://domain2:443,https://its-alias:443 
For more info: https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html
```

**Desktop (please complete the following information)**
 - Docker 20.10.14

**Additional context**
```
services:
  collabora:
    image: collabora/code:21.11.3.6.1
    restart: always
    container_name: collabora
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    environment:
      - aliasgroup1=https://domain.name.com:443
      - username=
      - password=
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=9980
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
```
After switching to aliasgroup
`docker logs `
```
wsd-00001-00040 2022-04-12 07:55:44.586542 +0000 [ websrv_poll ] WRN  convert-to: Requesting address is denied: xxx.xxx.xxx.xxx| wsd/COOLWSD.cpp:3015
```
