### ISSUE TITLE
Server only accessible from internal network

### ISSUE THREAD

**Issue by Ron161** [CollaboraOnline/online#5031]
I tried to set up a CollaboraOnline server on a QNAP NAS with a nextcloud instance behind a nginx reverse proxy. When accessing the local ip of the CollaboraOnline server I get a "ok" but when trying to go through the reverse proxy i get a 504 Gateway Timeout.
I tested the nginx configuration by installing the Code server docker on my PC and changing only the host in the proxy which worked like a charm. 
I am starting the Code Server with docker compose and the following config:

```

version: "3"
services:
  code:
    image: 'collabora/code'
    restart: unless-stopped
    environment:
      - "server_name=code,server.adress.com"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    cap_add:
      - MKNOD
    ports:
      - '9980:9980'
```

and i terminate the SSL connection at the proxy (using nginx proxy manager) with the follwoing config

```
# static files
location ^~ /browser {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# WOPI discovery URL
location ^~ /hosting/discovery {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# Capabilities
location ^~ /hosting/capabilities {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;

 }
# main websocket
location ~ ^/cool/(.*)/ws$ {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $http_host;
  proxy_read_timeout 36000s;
}

# download, presentation and image upload
location ~ ^/(c|l)ool {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# Admin Console websocket
location ^~ /cool/adminws {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $http_host;
  proxy_read_timeout 36000s;
}
```

as the connection to a code server on my pc works and even editing documents via nextcloud works i assume the error must lie within the code server docker. 

I am using the following
QNAP TS-230
collabora/code:22.05.4.1.1 (also tried 21.11.3.4.1 and 6.4.14.3)
