### ISSUE TITLE
Filename overlaps menu in compact mode

### ISSUE THREAD

**Issue by relikd** [CollaboraOnline/online#5407]
**Describe the bug**
The filename field (which is also used to rename the file) is displayed on top of the menu bar.
This does not happen for `user_interface.mode = tabbed` but only for `user_interface.mode = compact`.

The affected div has the following css:
```css
@media screen and (min-width: 1200px)
nav:not(.hasnotebookbar).main-nav #document-titlebar {
  position: absolute;
  left: 50%;
}
```
which is just shown in the middle of the screen, regardless of other elements.

**To Reproduce**
Resize the browser window until the issue emerges (e.g. simulate a small screen size).

**Expected behavior**
The filename should be shown right of the menu bar.

**Actual behavior**
The filename / title is misplaced.

**Screenshots**
![screen](https://user-images.githubusercontent.com/1321720/199311313-478d6d94-786f-4426-bd2a-83ffb65bfcc9.png)

**Desktop (please complete the following information)**
 - OS: macOS
 - Browser: Firefox
 - Version: 106

**Additional context**
Docker setup with COOLWSD 22.05.7.2 (git hash: https://github.com/CollaboraOnline/online/commit/b6395462873df146ca012b3f7c0dfda540b99152)
