### ISSUE TITLE
Collabora behind Traefik not working

### ISSUE THREAD

**Issue by Y0ngg4n** [CollaboraOnline/online#5827]
**Describe the bug**
I have deployed Collabora inside Kubernetes behind Traefik.
I have created deployed Collabora as Deployment with the following env variables:
```yaml
          env:
            - name: username
              value: "admin"
            - name: password
              valueFrom:
                secretKeyRef:
                  name: collabora
                  key: password
            - name: server_name
              value: office.example.com
            - name: domain
              value: office\.example\.com
            - name: extra_params
              value: "--o:ssl.enable=false --o:ssl.termination=true"
```

I have created a IngressRouteTCP for it:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: collabora
  namespace: storage
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`office.example.com`)
      services:
        - name: collabora
          port: 9980
  tls:
    secretName: office-tls
    passthrough: false
```

If i try to access collabora now via https://office.example.com i get a `ERR_HTTP2_PROTOCOL_ERROR` in the browser and
following error in the collabora logs:
```
wsd-00001-00041 2023-02-10 09:54:03.631460 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
wsd-00001-00041 2023-02-10 09:54:16.939634 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
wsd-00001-00041 2023-02-10 09:54:18.133312 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
wsd-00001-00041 2023-02-10 09:54:23.286221 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
wsd-00001-00041 2023-02-10 09:54:53.468997 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
wsd-00001-00041 2023-02-10 09:55:53.726275 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [PRI * HTTP/2.0 ...]: Not found| wsd/COOLWSD.cpp:3787
``` 

**To Reproduce**
1. Deploy Collabora behind traefik with SSL termination by Traefik
2. Try to access collabora

**Expected behavior**
I can access Collabora

**Actual behavior**
I get the above error messages

**Desktop (please complete the following information)**
 - OS: [e.g. iOS] Arch Linux
 - Browser: [e.g. chrome, safari] Firefox, Brave, Chrome, Opera
