### ISSUE TITLE
Docker container restarts (78) with logs: "Unknown option specified: use-env-vars"

### ISSUE THREAD

**Issue by sebastianfischer** [CollaboraOnline/online#7455]
### Describe the Bug

After building docker-container with collabora version cp-23.05.5-1, the container goes into restart loop (docker ps shows: restarting (78)". docker-compose logs shows error "Unknown option specified: use-env-vars"
Rebuilding container with version cp-23.05.4-2 works without problems

I would guess it has to do something with https://github.com/CollaboraOnline/online/pull/7160

### Steps to Reproduce

1. Build docker container with version cp-23.05.5-1 with `docker build --no-cache --secret id=secret_key,src=/tmp/collabora.secret --build-arg type=cool -t xxxxxx/collabora:cp-23.05.5-1 .`
2. start via `docker_compose up -d` (docker-compose.yml farther down)  
3. output `docker ps` -> `cd4025743d9a   xxxxxx/collabora:cp-23.05.5-1   "/start-collabora-on…"   12 seconds ago   Restarting (78) Less than a second ago `
4. output `docker-compose logs` -> 
```
collabora-test    | Certificate request self-signature ok
collabora-test    | subject=C = DE, ST = BW, L = Stuttgart, O = Dummy Authority, CN = localhost
collabora-test    | Unknown option specified: use-env-vars
collabora-test    | Certificate request self-signature ok
collabora-test    | subject=C = DE, ST = BW, L = Stuttgart, O = Dummy Authority, CN = localhost
collabora-test    | Unknown option specified: use-env-vars
....
collabora-test    | Certificate request self-signature ok
collabora-test    | subject=C = DE, ST = BW, L = Stuttgart, O = Dummy Authority, CN = localhost
collabora-test    | Unknown option specified: use-env-vars
```
...in forever loop.

#### docker-compose.yml

docker-compose (with ansible variables)

```
version: "3"

services:
  collabora:
    image: collabora:cp-23.05.5-1
    container_name: collabora
    restart: always
    environment:
      - username={{ collabora_admin }}
      - password={{ collabora_password }}
      - server_name={{ docker_domain }}
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - dictionaries='de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru'
    networks:
      - proxy
    labels:
      #unrelated traefik stuff

networks:
  proxy:
    external: true
```

### Expected Behavior

collabora should start

### Actual Behavior

container goes into restart loop

### Server

(Please complete the following information)
 - **OS:** Ubuntu 20.04.6
- **Docker:** Docker version 24.0.6, build ed223bc
