### ISSUE TITLE
Nextcloud stopped beeing able to connect to Collabora with Docker Image 23.05.5.1.1 and up

### ISSUE THREAD

**Issue by aschlenker** [CollaboraOnline/online#7697]
### Describe the Bug

I'm running Nextcloud and Collabora in seperate docker stacks with portainer behind nginx proxy manager.

After I did upgrades I found that Nextcloud cannot connect to Collabora anymore with container 23.05.5.1.1 and up.

The last version that works for the configuration below is 23.05.4.2.1.

No changes to configuration. This could be a bug or a misconfiguration on my part, but I checked the collabora proxy settings docs and it seems nothing changed since I wrote my configuration.

### Steps to Reproduce

My configuration is as follows:

```yml
version: '3'

services:
  app:
    image: collabora/code:latest
    container_name: collabora_app
    restart: unless-stopped
    expose:
      - 9980
    cap_add:
      - MKNOD
    volumes:
      - app_data:/config
    environment:
      - aliasgroup1=https://collabora.mydomain.com:443,https://nextcloud.mydomain.com:443
      - username=admin
      - password=PASSWORD
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    networks:
      - npm_frontend

volumes:
  app_data:

networks:
  npm_frontend:
    external: true
```

```yml
version: "3"

services:
    app:
        image: nextcloud:latest
        container_name: nextcloud_app
        restart: unless-stopped
        expose:
            - 80
        environment:
            MYSQL_HOST: db
            MYSQL_USER: nextcloud
            MYSQL_DATABASE: nextcloud
            MYSQL_PASSWORD: PASSWORD
            REDIS_HOST: nextcloud-cache
            REDIS_HOST_PASSWORD: PASSWORD
            NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.mydomain.com collabora.mydomain.com
            OVERWRITEPROTOCOL: https
        volumes:
            - app_data:/var/www/html
        networks:
            - npm_frontend
            - backend
        depends_on:
            - db
            - cache

    db:
        image: mariadb:10.11
        container_name: nextcloud_db
        restart: unless-stopped
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        environment:
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: PASSWORD
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - backend

    cache:
        image: redis:alpine
        container_name: nextcloud_cache
        restart: unless-stopped
        hostname: nextcloud-cache
        command: redis-server --requirepass PASSWORD
        volumes:
            - cache_data:/data
        networks:
            - backend

volumes:
    app_data:
    db_data:
    cache_data:

networks:
    npm_frontend:
        external: true
    backend:
```

```nginx
# in nginx proxy manager:
#
# Scheme: http
# Forward Hostname: collabora_app
# Forward Port: 9980
# Block Common Exploits: Checked
# Websocket Support: Checked
# SSL Certificate: a Let't Encrypt cert
# Force SSL: Checked
# HTTP/2 Support: Checked
# HSTS Enabled: Checked
#
# Advanced Configuration:

# static files
location ^~ /browser {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# WOPI discovery URL
location ^~ /hosting/discovery {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# Capabilities
location ^~ /hosting/capabilities {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# main websocket
location ~ ^/cool/(.*)/ws$ {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $http_host;
  proxy_read_timeout 36000s;
}

# download, presentation and image upload
location ~ ^/(c|l)ool {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Host $http_host;
}

# Admin Console websocket
location ^~ /cool/adminws {
  proxy_pass $forward_scheme://$server:$port;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Host $http_host;
  proxy_read_timeout 36000s;
}
```

### Expected Behavior

Clicking on Test.odt in Nextcloud opens Collabora.

### Actual Behavior

Nextcloud is showing me the error message "Failed to establish socket connection or socket connection closed unexpectedly. The reverse proxy might be misconfigured, please contact the administrator. For more info on proxy configuration please check https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html".

### Server

 - **Collabora version:** 23.05.5.4.1 (:latest tag)
 - **Nextcloud version:** 27.1.3-apache (:latest tag)
 - **Server version:** Ubuntu 22.04.3 LTS

### Desktop

 - **OS and version:** macOS 14.1.1
 - **Browser and version:** Firefox 121.0b1
