### ISSUE TITLE
Setting multiple aliasgroup ENV's stopped working after upgarde

### ISSUE THREAD

**Issue by JFossey** [CollaboraOnline/online#7847]
### Describe the Bug

Setting multiple `aliasgroup` in docker ENV only works for first 2, from `aliasgroup3` on it stops working and nextcloud instances configured in `aliasgroup3` get a `You have not configured the allow-list for WOPI requests...` error.

### Steps to Reproduce

1. Have a working installation of Collabora online with 2 or more nextcloud instances connected
2. Upgrade to the latest version NC 27 and Collabora docker instance.
3. Go to nextcloud instances and visit office admin.

### Expected Behavior

Should show a green connected checkmark in office admin and be able to open office documents.

### Actual Behavior

Shows a WOPI error and shows a could not connect error and cant open office documents.

### Screenshots

![image](https://github.com/CollaboraOnline/online/assets/4981545/98c86c69-20d2-4f21-81e6-2cc976ccaefe)

### Additional Context

This was working until recent upgrades of both Nextcloud and Collabora.

Logs show the office Collabora host and the first nextcloud host configured at alias 2 but host configured alias 3 does not show up in the logs.

```
INF  Adding trusted LOK_ALLOW host: [https://office.domain.tld:443]| wsd/COOLWSD.cpp:326
INF  Adding trusted LOK_ALLOW host: [https://nc1.domain.tld:443]| wsd/COOLWSD.cpp:326
```

**Comment by mmeeks** [comment]
This is interesting =)  I think for large numbers of servers we would probably want to use the remote-config feature documented here: https://sdk.collaboraonline.com/docs/installation/Configuration.html?highlight=remote_config#remote-dynamic-configuration which should also be easier to administer. As long as you can serve that file from a https:// with good certificate you should be fine.

Beyond that - we should diagnose & fix any regression in the configurability ...

Andras can you take a look here ? =)

**Comment by timar** [comment]
I wonder, if https://github.com/CollaboraOnline/online/pull/10379 fixed this.

**Comment by Rash419** [comment]
@JFossey  I think https://github.com/CollaboraOnline/online/pull/10379 fixes the problem. I am closing this issue. If issue persist please re-open it. Thanks

**Comment by Deaddy** [comment]
I think we got confused here, the code looks like the fix for https://github.com/CollaboraOnline/online/issues/7508

It is still not possible to set multiple aliasgroups via env and this remote configuration thing is orthogonal to declarative deployment.

Env is populated just fine, e.g. running `env` in the container yields:
```
aliasgroup4=reach.sciebo.de
aliasgroup1=dlr.sciebo.de
aliasgroup2=khm-test.sciebo.de
aliasgroup3=tastefultest.sciebo.de
aliasgroup5=sns-staging.sciebo.de
aliasgroup6=sns-testing.sciebo.de
```
Log as mentioned by OP adds these to LOK_ALLOW but not to WOPI hosts:
```
wsd-00001-00001 2024-11-28 13:47:18.306200 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [dlr.sciebo.de]| wsd/COOLWSD.cpp:284
wsd-00001-00001 2024-11-28 13:47:18.306211 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [khm-test.sciebo.de]| wsd/COOLWSD.cpp:284
wsd-00001-00001 2024-11-28 13:47:18.306218 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [tastefultest.sciebo.de| wsd/COOLWSD.cpp:284
wsd-00001-00001 2024-11-28 13:47:18.306224 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [reach.sciebo.de]| wsd/COOLWSD.cpp:284
wsd-00001-00001 2024-11-28 13:47:18.306232 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [sns-staging.sciebo.de]| wsd/COOLWSD.cpp:284
wsd-00001-00001 2024-11-28 13:47:18.306238 +0000 [ coolwsd ] INF  Adding trusted LOK_ALLOW host: [sns-testing.sciebo.de]| wsd/COOLWSD.cpp:284
```

However, still only the first host to connect is allowed as WOPI host, e.g. if first connecting with sns-staging, all further hosts produce the log message
```
wsd-00001-00036 2024-11-28 13:48:08.021037 +0000 [ websrv_poll ] ERR  Only allowed host is: sns-staging.sciebo.de, To use multiple host/aliases check alias_groups tag in configuration| wsd/HostUtil.cpp:231
```
and corresponding error messages for the user who is unable to open files.

**Comment by Rash419** [comment]
@Deaddy let me check again : )

**Comment by Rash419** [comment]
@Deaddy I quickly tried the same CODE version

For me it is successfully adding the trusted WOPI host
```
wsd-00001-00001 2024-11-28 14:26:48.824452 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [reach.sciebo.de].| wsd/HostUtil.cpp:54
wsd-00001-00001 2024-11-28 14:26:48.824459 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [dlr.sciebo.de].| wsd/HostUtil.cpp:54
wsd-00001-00001 2024-11-28 14:26:48.824463 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [khm-test.sciebo.de].| wsd/HostUtil.cpp:54
wsd-00001-00001 2024-11-28 14:26:48.824467 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [tastefultest.sciebo.de].| wsd/HostUtil.cpp:54
wsd-00001-00001 2024-11-28 14:26:48.824470 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [sns-staging.sciebo.de].| wsd/HostUtil.cpp:54
wsd-00001-00001 2024-11-28 14:26:48.824474 +0000 [ coolwsd ] INF  Adding trusted WOPI host: [sns-testing.sciebo.de].| wsd/HostUtil.cpp:54
```

This is how my `collabora` block in `my_values.yaml` looks like:

```
collabora:
  aliasgroups:
    - host: "http://reach.sciebo.de"
    - host: "http://dlr.sciebo.de"
    - host: "http://khm-test.sciebo.de"
    - host: "http://tastefultest.sciebo.de"
    - host: "http://sns-staging.sciebo.de"
    - host: "http://sns-testing.sciebo.de"
  extra_params: --o:ssl.enable=false
```

I am assuming all the WOPIHost domain are of different WOPIHost server. If not, for example `sns-staging.sciebo.de` and `sns-testing.sciebo.de` aliases of each other configuration would be

```
collabora:
  aliasgroups:
    - host: "http://reach.sciebo.de"
    - host: "http://dlr.sciebo.de"
    - host: "http://khm-test.sciebo.de"
    - host: "http://tastefultest.sciebo.de"
    - host: "http://sns-staging.sciebo.de"
      aliases:
        - "http://sns-testing.sciebo.de"
  extra_params: --o:ssl.enable=false
```

Let me know if you any doubts/concerns : )
