### ISSUE TITLE
no-new-privileges not working

### ISSUE THREAD

**Issue by azertylr** [CollaboraOnline/online#8164]
Hello,

When I run collabora with no-new-privileges=true, the server doesn't start

Collabora version: 23.05.7.5
```
code:
    image: collabora/code:latest
    container_name: collabora
    user: "cool" 
    cap_add:
      - SYS_CHROOT
      - SYS_ADMIN
      - MKNOD
      - FOWNER
      - CHOWN
      - SETPCAP
    security_opt:
      - no-new-privileges=true
```
I have the following error:
```
 ERR  Capability cap_chown is not set for the coolforkit program.| kit/ForKit.cpp:228
 ERR  Capability cap_mknod is not set for the coolforkit program.| kit/ForKit.cpp:228
 ERR  Capability cap_sys_chroot is not set for the coolforkit program.| kit/ForKit.cpp:228
 ERR  Capability cap_fowner is not set for the coolforkit program.| kit/ForKit.cpp:228
```

And the server is restarting in loop.

Thanks

**Comment by azertylr** [comment]
it is working with "security.capabilities=false"

I don't know if this recommanded.


  ```
code:
    image: collabora/code:latest
    user: "cool"
    environment:
       - extra_params=--o:security.capabilities=false --o:ssl.enable=true
    security_opt:
      - no-new-privileges=true
```
