### ISSUE TITLE
Version 24.04.5.2.1 broken on rootless podman

### ISSUE THREAD

**Issue by witchent** [CollaboraOnline/online#9534]
### Describe the Bug
I am using the docker image of collabora in a rootless podman setup and the newest update doesn't let me run it anymore. Just changing the version tag in the compose file to 24.04.5.1.1 let me run it in the exact same environment, so I don't think it is to much related to https://github.com/CollaboraOnline/online/issues/2800.

### Steps to Reproduce
``docker-compose.yml`` part:
```
  nextcloud-collabora:
    container_name: collabora
    image: docker.io/collabora/code:24.04.5.2.1
    restart: on-failure
    cap_add:
     - MKNOD
    ports:
      - 127.0.0.1:9980:9980
    environment:
      aliasgroup1: mydomain
      username: username
      password: securepassword
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
```

### Expected Behavior
Collabora to run and serve the discovery endpoint.

### Actual Behavior
Collabora runs but I cannot even curl the discovery url. 
While starting up I get the following errors in the log:
```
collabora  | kit-00024-00024 2024-07-18 08:42:51.907653 +0000 [ kit_spare_001 ] TRC  File [/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS//etc/localtime] is already up-to-date.| common/JailUtil.cpp:549
collabora  | kit-00024-00024 2024-07-18 08:42:51.907837 +0000 [ kit_spare_001 ] DBG  Initialized jail files in 4432ms| kit/Kit.cpp:3196
collabora  | chroot("/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS/") failed (EPERM: Operation not permitted)
collabora  | kit-00024-00024 2024-07-18 08:42:51.907882 +0000 [ kit_spare_001 ] INF  chroot("/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS/")| kit/Kit.cpp:3211
collabora  | kit-00024-00024 2024-07-18 08:42:51.907919 +0000 [ kit_spare_001 ] FTL  chroot("/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS/") failed (EPERM: Operation not permitted)| kit/Kit.cpp:3214
collabora  | Forced Exit with code: 70
collabora  | kit-00024-00024 2024-07-18 08:42:51.907934 +0000 [ kit_spare_001 ] FTL  Forced Exit with code: 70| common/Util.cpp:847
collabora  | frk-00019-00019 2024-07-18 08:42:51.917946 +0000 [ forkit ] WRN  No live Kits exist, and we are not terminating yet.| kit/ForKit.cpp:312
collabora  | notcoolmount: unmount failed to detach [/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS/lo]: Operation not permitted.
collabora  | notcoolmount: forced unmount of [/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS/lo] failed: Operation not permitted.
collabora  | notcoolmount: unmount failed to detach [/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS]: Operation not permitted.
collabora  | notcoolmount: forced unmount of [/opt/cool/child-roots/1-c23b8cb8/FV5Ht6mkNAy778qS] failed: Operation not permitted.
collabora  | wsd-00001-00018 2024-07-18 08:43:05.492567 +0000 [ prisoner_poll ] TRC  Poll completed with 0 live polls max (17999971us)(timedout)| net/Socket.cpp:446
```

Also, periodically the following error is logged:
```
collabora  | wsd-00001-00001 2024-07-18 08:45:32.745781 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4392
collabora  | wsd-00001-00001 2024-07-18 08:45:52.746026 +0000 [ coolwsd ] INF  Waiting for a new child for a max of 20000ms| wsd/COOLWSD.cpp:4392
```

### Desktop
(Please complete the following information)
 - **Collabora version:** 24.04.5.2.1
 - **OS and version:** Arch Linux (current updates)
 - **Docker-Environment**: Podman-rootless 5.1.2 serving the docker.socket, docker-compose 2.29.0 to actually execute the compose file
